#!/usr/bin/env ruby

require './test_mocks.rb'

require './ide.rb'
require './sr-links.rb'

m = PrintingMessage.new

idePlugin = IDEPlugin.new
idePlugin.privmsg(m)

srLinksPlugin = SRLinksPlugin.new

m.message = "nothing here"
srLinksPlugin.listen(m)

m.message = "#123"
srLinksPlugin.listen(m)

m.message = "things #123 here"
srLinksPlugin.listen(m)

m.message = "things not 0147 here"
srLinksPlugin.listen(m)

m.message = "things not #0147here either"
srLinksPlugin.listen(m)

m.message = "trac #456"
srLinksPlugin.privmsg(m)

m.message = "trac 258"
srLinksPlugin.privmsg(m)

m.message = "trac PageName"
srLinksPlugin.privmsg(m)

m.message = "trac Spacey Page Name"
srLinksPlugin.privmsg(m)
