#!/usr/bin/env ruby

require './test_mocks.rb'

require './ide.rb'
require './trac.rb'

m = PrivMessage.new

idePlugin = IDEPlugin.new
idePlugin.privmsg(m)

tracPlugin = TracPlugin.new

m.message = "nothing here"
tracPlugin.listen(m)

m.message = "#123"
tracPlugin.listen(m)

m.message = "things #123 here"
tracPlugin.listen(m)

m.message = "things not 0147 here"
tracPlugin.listen(m)

m.message = "trac #456"
tracPlugin.privmsg(m)

m.message = "trac 258"
tracPlugin.privmsg(m)

m.message = "trac PageName"
tracPlugin.privmsg(m)

m.message = "trac Spacey Page Name"
tracPlugin.privmsg(m)
