#!/usr/bin/env ruby

# A mock of the rbot Plugin base
class Plugin
	def map(a)
	end
	def register(a)
	end
end

class PrivMessage
	attr_accessor :message

	def reply(thing)
		print thing, "\n"
	end
end

require './ide.rb'
require './trac.rb'

m = PrivMessage.new

idePlugin = IDEPlugin.new
idePlugin.privmsg(m)

tracPlugin = TracPlugin.new

m.message = "nothing here"
tracPlugin.listen(m)

m.message = "things #123 here"
tracPlugin.listen(m)

m.message = "trac #456"
tracPlugin.privmsg(m)

m.message = "trac PageName"
tracPlugin.privmsg(m)

m.message = "trac Spacey Page Name"
tracPlugin.privmsg(m)
