#!/usr/bin/env ruby

require './test_mocks.rb'

if VERSION < "1.9.1"
  class File
    def self.absolute_path(rel_path)
      dir = File.dirname($0)
      abs = dir + '/' + rel_path
      return abs
    end
  end
end

msg = PrivMessage.new

if ARGV.length == 0
  print 'Usage: try [FILE [FILE ..]]', "\n"
  print 'Tries to run each of the files as an rbot plugin.', "\n"
  print '* Assumes a plugin name of BeesPlugin for bees.rb.', "\n"
  print '* Assumes a response to privmsg with no incoming message.', "\n"
end

ARGV.each do|name|
  if not File.exist?(name)
    print "File #{name} doesn't exist! Skipping."
    next
  end

  if not name.end_with?('.rb')
    print "File #{name} doesn't look like a ruby file! Skipping."
    next
  end

  asb_name = File.absolute_path(name)
  require asb_name

  nice_name = File.basename(name, '.rb')
  class_name = nice_name.capitalize + 'Plugin'
  #print class_name, "\n"
  inst = Kernel.const_get(class_name).send('new')
  inst.privmsg(msg)

end
